---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker
inputs:
- name: repo
- name: stemcell
  optional: true
run:
  path: repo/ci/tasks/integration-test/run.sh
