---
name: openvpn

releases:
- name: "openvpn"
  version: "5.3.0"
  url: "https://bosh.io/d/github.com/dpb587/openvpn-bosh-release?v=5.3.0"
  sha1: "91ce6cba681dcc25f070a3ee0c546efbcaa15d6d"
- name: os-conf
  version: 11
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=11
  sha1: 651f10a765a2900a7f69ea07705f3367bd8041eb

stemcells:
- alias: "default"
  os: "ubuntu-xenial"
  version: "latest"

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1

instance_groups:
- name: openvpn
  jobs:
  - name: openvpn
    release: openvpn
    properties:
      server: ((vpn_network)) ((vpn_network_mask))
      tls_server: ((server_key_pair))
      dh_pem: |
        -----BEGIN DH PARAMETERS-----
        MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
        LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
        2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
        /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
        9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
        fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
        -----END DH PARAMETERS-----
  - name: disable_agent
    release: os-conf
    properties: {}
  instances: 1
  stemcell: default
  vm_type: t2.nano
  azs:
  - z1
  networks:
  - name: default

variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: server_key_pair
  type: certificate
  options:
    ca: ca
    common_name: openvpn
    key_usage:
    - digital_signature
    - key_encipherment
    extended_key_usage:
    - server_auth
